apiVersion: apps/v1
kind: Deployment
metadata:
  name: amq-broker-72-scaledown-controller-openshift-deployment
  labels:
    app: amq-broker-72-scaledown-controller-openshift-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amq-broker-72-scaledown-controller-openshift-app
  template:
    metadata:
      labels:
        app: amq-broker-72-scaledown-controller-openshift-app
    spec:
      serviceAccountName: amq-broker-72-scaledown-controller-openshift-sa
      containers:
      - name: main
        image: registry.access.redhat.com/amq-broker-7-tech-preview/amq-broker-72-scaledown-openshift:0.4
        args:
        - '--localOnly'
        - '--v'
        - '3'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amq-broker-72-scaledown-controller-openshift-sa
  labels:
    app: amq-broker-72-scaledown-controller-openshift-app
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: amq-broker-72-scaledown-controller-openshift-role
  labels:
    app: amq-broker-72-scaledown-controller-openshift-app
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: amq-broker-72-scaledown-controller-openshift-rb
  labels:
    app: amq-broker-72-scaledown-controller-openshift-app
subjects:
  - kind: ServiceAccount
    name: amq-broker-72-scaledown-controller-openshift-sa
roleRef:
  kind: Role
  name: amq-broker-72-scaledown-controller-openshift-role
  apiGroup: rbac.authorization.k8s.io
