= POC ACTIVITIES



== STAGE 1:  Install all necessary components (templates, images/streams)

=== STAGE 1: Define Pre-Requisites 

=== STAGE 1: Activities

* Activity 1: Install ImageStreams for AMQ Broker and ScaleDown controller in namespace /*openshift*/

[source, bash]
----
oc login -u system:admin
oc replace --force -f https://raw.githubusercontent.com/jboss-container-images/jboss-amq-7-broker-openshift-image/72-1.1.GA/amq-broker-7-image-streams.yaml -n openshift
oc replace --force -f https://raw.githubusercontent.com/jboss-container-images/jboss-amq-7-broker-openshift-image/72-1.1.GA/amq-broker-7-scaledown-controller-image-streams.yaml -n openshift
----

* Activity 2: Install AMQ Templates in namespace *openshift*

[source, bash]
----
for template in amq-broker-72-basic.yaml \
 amq-broker-72-ssl.yaml \
 amq-broker-72-custom.yaml \
 amq-broker-72-persistence.yaml \
 amq-broker-72-persistence-ssl.yaml \
 amq-broker-72-persistence-clustered.yaml \
 amq-broker-72-persistence-clustered-ssl.yaml;
 do
  oc replace --force -f \
 https://raw.githubusercontent.com/jboss-container-images/jboss-amq-7-broker-openshift-image/72-1.1.GA/templates/${template} -n openshift
  done
----


=== STAGE 1: Define Success Criteria


---


== STAGE 2:  Install Broker in Clustered (SSL) and Persistent Mode (3 PODs) (This to be defined)

=== STAGE 2:  Define Pre-Requisites 
- Compatible Storage available in the cluster
- Enough Resources

=== STAGE 2: Activities

* Activity 1: Install ScaleDown controller in namespace *amq-pocs*

[source, bash]
----
oc create -n amq-pocs -f https://raw.githubusercontent.com/jboss-container-images/jboss-amq-7-broker-openshift-image/72-1.1.GA/templates/amq-broker-72-persistence-clustered-controller.yaml
deployment.apps/amq-broker-72-scaledown-controller-openshift-deployment created
serviceaccount/amq-broker-72-scaledown-controller-openshift-sa created
role.rbac.authorization.k8s.io/amq-broker-72-scaledown-controller-openshift-role created
rolebinding.rbac.authorization.k8s.io/amq-broker-72-scaledown-controller-openshift-rb created
----

=== STAGE 2:  Define Success Criteria
- Define Destinations (check they are there) Topics/Queues
- Scale-Down controller has to be installed as well to monitor PVCs


---


== STAGE 3:  Client/Consumers for ingestion of data

=== STAGE 3:  Define Pre-Requisites 
- 

=== STAGE 3: Activities
- 

=== STAGE 3:  Define Success Criteria

- 



---


== STAGE 4:  Setup AMQ & OCP Objects for HA & Scale Up/Downs

=== STAGE 3:  Define Pre-Requisites 
- 

=== STAGE 3: Activities
- Actvitiy 1: Installing Scaledown Controller
* link:https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/deploying_amq_broker_on_openshift_container_platform/#install-journal-recovery-broker-ocp[7.1. Installing the scaledown controller]


- Activity 2: Configure ScaleDown Controller
* link:https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/deploying_amq_broker_on_openshift_container_platform/#using_pod_draining_broker-ocp[7.2. Using the scaledown controller]

- Activity 3: 



=== STAGE 3:  Define Success Criteria

- 




