kind: List
apiVersion: v1
metadata:
  name: amq-broker-7-scaledown-controller-image-streams
  annotations:
    description: ImageStream definitions for Red Hat AMQ Broker 7.2 Scaledown Controller Container Image
    openshift.io/provider-display-name: Red Hat, Inc.
items:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: amq-broker-72-scaledown-controller-openshift
    annotations:
      openshift.io/display-name: Red Hat AMQ Broker 7.2 Scaledown Controller
      openshift.io/provider-display-name: Red Hat, Inc.
  spec:
    lookupPolicy:
      local: true  
    tags:
    - name: '1.0'
      annotations:
        description: Red Hat AMQ Broker 7.2 Scaledown Controller image.
        iconClass: icon-jboss
        tags: messaging,amq,jboss,xpaas
        supports: amq:7.2,messaging:1.0,messaging:1.1
        version: '1.0'
      from:
        kind: DockerImage
        name: registry.access.redhat.com/amq-broker-7-tech-preview/amq-broker-72-scaledown-openshift:0.4
